"""add guidance_quote to earnings_insights

Revision ID: 7dd85f0d2447
Revises: fe2eb5a292a1
Create Date: 2026-09-10 21:50:27.257922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd85f0d2447'
down_revision: Union[str, Sequence[str], None] = 'fe2eb5a292a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # commands generated by Alembic
    op.add_column('earnings_insights', sa.Column('guidance_quote', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('earnings_insights', 'guidance_quote')
