"""create earnings_ingestion_jobs

Revision ID: 90f8eff0fcef
Revises: 7dd85f0d2447
Create Date: 2026-09-17 22:40:25.108277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f8eff0fcef'
down_revision: Union[str, Sequence[str], None] = '7dd85f0d2447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_ingestion_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_attempted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_earnings_ingestion_jobs_status_next_attempt_at', 'earnings_ingestion_jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_earnings_ingestion_jobs_ticker_earnings_date', 'earnings_ingestion_jobs', ['ticker', 'earnings_date'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### adjust! ###
    op.drop_index('ix_earnings_ingestion_jobs_ticker_earnings_date', table_name='earnings_ingestion_jobs')
    op.drop_index('ix_earnings_ingestion_jobs_status_next_attempt_at', table_name='earnings_ingestion_jobs')
    op.drop_table('earnings_ingestion_jobs')
    # ### end Alembic commands ###
