"""create companies, scan_runs, factor_scores

Revision ID: b4a440aaa237
Revises: 
Create Date: 2026-07-09 14:44:28.223451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4a440aaa237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.BigInteger(), nullable=False),
    sa.Column('value_score', sa.Numeric(), nullable=True),
    sa.Column('momentum_score', sa.Numeric(), nullable=True),
    sa.Column('quality_score', sa.Numeric(), nullable=True),
    sa.Column('solvency_score', sa.Numeric(), nullable=True),
    sa.Column('volatility_score', sa.Numeric(), nullable=True),
    sa.Column('composite_score', sa.Numeric(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('raw_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_scores_ticker_computed_at', 'factor_scores', ['ticker', sa.literal_column('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_factor_scores_ticker_computed_at', table_name='factor_scores')
    op.drop_table('factor_scores')
    op.drop_table('scan_runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
