"""create earnings_backfill_progress

Revision ID: c6e3e0c723dc
Revises: 90f8eff0fcef
Create Date: 2026-09-18 21:51:09.985769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e3e0c723dc'
down_revision: Union[str, Sequence[str], None] = '90f8eff0fcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_backfill_progress',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('quarters_ingested', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    # NOTE: autogenerate also proposed dropping ix_earnings_chunks_embedding_hnsw
    # and ix_memo_embeddings_embedding_hnsw here - both are real HNSW indexes
    # (architecture.md §4) created by raw SQL in earlier migrations, which
    # SQLAlchemy's Index construct can't fully express, so autogenerate always
    # sees them as "missing" from the ORM metadata. Removed by hand - this
    # migration only adds earnings_backfill_progress. See migration
    # 90f8eff0fcef for the same false positive.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings_backfill_progress')
    # ### end Alembic commands ###
