"""create llm_calls, tool_calls, add request_id to chat_messages

Revision ID: f2b45d71b32f
Revises: c6e3e0c723dc
Create Date: 2026-09-23 23:28:47.950539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b45d71b32f'
down_revision: Union[str, Sequence[str], None] = 'c6e3e0c723dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_created_at', 'llm_calls', ['created_at'], unique=False)
    op.create_index('ix_llm_calls_request_id', 'llm_calls', ['request_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_request_id', 'tool_calls', ['request_id'], unique=False)
    op.add_column('chat_messages', sa.Column('request_id', sa.String(), nullable=True))
    op.create_index('ix_chat_messages_request_id', 'chat_messages', ['request_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_earnings_chunks_embedding_hnsw
    # and ix_memo_embeddings_embedding_hnsw here - both are real HNSW indexes
    # created by raw SQL in earlier migrations, which SQLAlchemy's Index
    # construct can't fully express, so autogenerate always sees them as
    # missing. Removed by hand - this migration only adds
    # llm_calls/tool_calls/chat_messages.request_id.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_request_id', table_name='chat_messages')
    op.drop_column('chat_messages', 'request_id')
    op.drop_index('ix_tool_calls_request_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_llm_calls_request_id', table_name='llm_calls')
    op.drop_index('ix_llm_calls_created_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
